### ISSUE TITLE
Chinese in code is not awsome, Change Englist is well, I guess ...

### ISSUE THREAD

**Issue by wowiwj** [rovast/algorithm#2]
https://github.com/rovast/algorithm/blob/8721e049fc6c183cad84cf80233670b282588bf8/list/array_list_test.c#L5

**Comment by rovast** [comment]
> https://github.com/rovast/algorithm/blob/8721e049fc6c183cad84cf80233670b282588bf8/list/array_list_test.c#L5

Yeah, you are right. Create a PR
